// <auto-generated />
namespace Loja.Infrastruture.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class lojav6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lojav6));
        
        string IMigrationMetadata.Id
        {
            get { return "202302242126091_loja-v6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
